Cloudinary setup
Songaapp/songa.api pull request #40
Opened 2023-06-05 05:30 UTC by Martindevelops-songa

Rider documents uploading and getting now working.

2023-06-09 10:24 UTC, dennisngeno-songa requested changes

2023-06-09 10:24 UTC, dennisngeno-songa commented on src/app.ts
> +//app.use("/api/users/customer_agent", CustomerCareAgentRoutes);
Kindly uncomment this one, we need the changes for customer care agents

2023-06-09 10:24 UTC, dennisngeno-songa commented on src/controllers/RiderDocumentsControllers.ts
> +          console.log(docName);
Would you remove console logs and use the logger instead

2023-06-09 10:24 UTC, dennisngeno-songa commented on uploads/ID-back.png.png
Are we supposed to add images to the source code or to Cloudinary?

2023-06-09 10:36 UTC, dennisngeno-songa commented on src/controllers/RiderDocumentsControllers.ts
> +import { PrismaClient, Rider, RiderDocuments } from "@prisma/client";
Rider is not used

2023-06-09 10:36 UTC, dennisngeno-songa commented on src/controllers/RiderDocumentsControllers.ts
> +//import { checkRider } from "../helpers/user";
Would you remove the comment

2023-06-09 10:38 UTC, dennisngeno-songa commented on src/controllers/RiderDocumentsControllers.ts
> +          console.log(result, "result");
Code has been duplication. Would you make it DRY

2023-06-09 10:41 UTC, dennisngeno-songa commented on src/controllers/RiderDocumentsControllers.ts
> +          console.log(result, "result");
The function is also long

2023-06-11 08:48 UTC, Martindevelops-songa reviewed
good

2023-06-11 08:49 UTC, mog-rn approved these changes

2023-06-11 08:53 UTC, mog-rn commented on src/controllers/RiderDocumentsControllers.ts
> +import { checkRider } from "../helpers/user";
There is aduplicate identifier here an also on ine 4 for the checkRider.

2023-06-12 05:06 UTC, dennisngeno-songa commented
Still seeing images and console logs in the diff

2023-06-12 05:07 UTC, dennisngeno-songa commented
and faling tests

2023-06-21 10:09 UTC, closed without merging